// Written by scripts/artisan-tree.py from CoffeeMUD's Artisan.java
// (snapshot c1e556f): don't edit by hand, run the script again.
// CoffeeMUD is Copyright Bo Zimmerman, Apache-2.0.
import type { ArtisanSkill } from "./artisan";

export const ARTISAN_SKILLS: ArtisanSkill[] = [
  { id: "Proficiency_EdgedWeapon", name: "Edged Weapon Proficiency", level: 1, kind: "weapon", needs: [] },
  { id: "Skill_Recall", name: "Recall", level: 1, kind: "skill", word: "RECALL", auto: true, needs: [] },
  { id: "Searching", name: "Searching", level: 1, kind: "craft", word: "SEARCH", needs: [] },
  { id: "FireBuilding", name: "Fire Building", level: 1, kind: "craft", word: "LIGHT", needs: [] },
  { id: "Skill_Swim", name: "Swim", level: 1, kind: "skill", word: "SWIM", needs: [] },
  { id: "Bandaging", name: "Bandaging", level: 1, kind: "craft", word: "BANDAGE", needs: [] },
  { id: "ClanCrafting", name: "Clan Crafting", level: 1, kind: "craft", word: "CLANCRAFT", needs: [] },
  { id: "Skill_Write", name: "Write", level: 1, kind: "skill", word: "WRITE", needs: [] },
  { id: "Foraging", name: "Foraging", level: 1, kind: "craft", word: "FORAGE", stat: ["Wisdom", 9], needs: [] },
  { id: "Drilling", name: "Drilling", level: 1, kind: "craft", word: "DRILL", stat: ["Intelligence", 9], needs: [] },
  { id: "Hunting", name: "Hunting", level: 1, kind: "craft", word: "HUNT", stat: ["Dexterity", 9], needs: [] },
  { id: "Butchering", name: "Butchering", level: 1, kind: "craft", word: "BUTCHER", stat: ["Intelligence", 9], needs: [] },
  { id: "Fishing", name: "Fishing", level: 1, kind: "craft", word: "FISH", stat: ["Dexterity", 9], needs: [] },
  { id: "Chopping", name: "Wood Chopping", level: 1, kind: "craft", word: "CHOP", stat: ["Constitution", 9], needs: [] },
  { id: "Mining", name: "Mining", level: 1, kind: "craft", word: "MINE", stat: ["Strength", 9], needs: [] },
  { id: "Digging", name: "Gem Digging", level: 1, kind: "craft", word: "GDIG", stat: ["Strength", 9], needs: [] },
  { id: "Skill_WildernessLore", name: "Wilderness Lore", level: 1, kind: "skill", word: "WILDERNESSLORE", needs: [["Searching", 75], ["Foraging", 75]] },
  { id: "Skill_Autoswim", name: "AutoSwim", level: 1, kind: "skill", word: "AUTOSWIM", needs: [["Skill_Swim", 75]] },
  { id: "Shrooming", name: "Shrooming", level: 1, kind: "craft", word: "SHROOMING", needs: [["Foraging", 75]] },
  { id: "Farming", name: "Farming", level: 1, kind: "craft", word: "PLANT", needs: [["Foraging", 75]] },
  { id: "FoodPreserving", name: "Food Preserving", level: 1, kind: "craft", word: "FOODPRESERVING", needs: [["Foraging", 75]] },
  { id: "Shearing", name: "Shearing", level: 1, kind: "craft", word: "SHEAR", needs: [["Foraging", 75]] },
  { id: "Familiarity_EdgedWeapon", name: "Edged Weapon Familiarity", level: 1, kind: "weapon", needs: [["Proficiency_EdgedWeapon", 75], ["Drilling", 75]] },
  { id: "Speculate", name: "Speculating", level: 1, kind: "craft", word: "SPECULATE", needs: [["Foraging", 75], ["Drilling", 75], ["Hunting", 75], ["Fishing", 75], ["Chopping", 75], ["Mining", 75], ["Digging", 75]] },
  { id: "Sculpting", name: "Sculpting", level: 1, kind: "craft", word: "SCULPT", needs: [["Mining", 75]] },
  { id: "Smelting", name: "Smelting", level: 1, kind: "craft", word: "SMELTING", needs: [["FireBuilding", 75], ["Mining", 75]] },
  { id: "Pottery", name: "Pottery", level: 1, kind: "craft", word: "POT", needs: [["Digging", 75]] },
  { id: "Masonry", name: "Masonry", level: 1, kind: "craft", word: "MASONRY", needs: [["Mining", 75], ["Digging", 75]] },
  { id: "Composting", name: "Composting", level: 1, kind: "craft", word: "COMPOST", needs: [["Farming", 75]] },
  { id: "FoodPrep", name: "Food Prep", level: 1, kind: "craft", word: "FOODPREPPING", needs: [["FoodPreserving", 75]] },
  { id: "Cooking", name: "Cooking", level: 1, kind: "craft", word: "COOK", needs: [["FoodPreserving", 75]] },
  { id: "Baking", name: "Baking", level: 1, kind: "craft", word: "BAKING", needs: [["FoodPreserving", 75]] },
  { id: "Distilling", name: "Distilling", level: 1, kind: "craft", word: "DISTILLING", needs: [["FoodPreserving", 75], ["Drilling", 75], ["FireBuilding", 75]] },
  { id: "Landscaping", name: "Landscaping", level: 1, kind: "craft", word: "LANDSCAPE", needs: [["Composting", 0]] },
  { id: "MasterFarming", name: "Master Farming", level: 30, kind: "craft", word: "MPLANT", needs: [["Landscaping", 75], ["Farming", 100]] },
  { id: "Herbology", name: "Herbology", level: 1, kind: "craft", word: "HERBOLOGY", needs: [["FoodPrep", 75]] },
  { id: "Mycology", name: "Mycology", level: 1, kind: "craft", word: "MYCOLOGY", needs: [["FoodPrep", 75]] },
  { id: "Textiling", name: "Textiling", level: 1, kind: "craft", word: "TEXTILING", needs: [["Shearing", 75]] },
  { id: "Gardening", name: "Gardening", level: 1, kind: "craft", word: "GPLANT", needs: [["Composting", 75], ["Herbology", 75]] },
  { id: "Floristry", name: "Floristry", level: 1, kind: "craft", word: "FLORISTRY", needs: [["Skill_WildernessLore", 75], ["Herbology", 75]] },
  { id: "MasterForaging", name: "Master Foraging", level: 30, kind: "craft", word: "MFORAGE", needs: [["Foraging", 100], ["Distilling", 75], ["Herbology", 75]] },
  { id: "MasterBaking", name: "Master Baking", level: 30, kind: "craft", word: "MBAKE", needs: [["Baking", 100], ["MasterFarming", 75]] },
  { id: "MasterFoodPrep", name: "Master Food Prep", level: 30, kind: "craft", word: "MFOODPREPPING", needs: [["FoodPrep", 100], ["Gardening", 75]] },
  { id: "Proficiency_Staff", name: "Staff Proficiency", level: 1, kind: "weapon", needs: [["Fishing", 75]] },
  { id: "FishLore", name: "Fish Lore", level: 1, kind: "craft", word: "FISHLORE", needs: [["Fishing", 75]] },
  { id: "Irrigation", name: "Irrigation", level: 1, kind: "craft", word: "IRRIGATE", needs: [["Composting", 75], ["FishLore", 75]] },
  { id: "MasterGardening", name: "Master Gardening", level: 30, kind: "craft", word: "MGPLANT", needs: [["Gardening", 100], ["MasterFoodPrep", 75]] },
  { id: "Tanning", name: "Tanning", level: 1, kind: "craft", word: "TAN", needs: [["Butchering", 75]] },
  { id: "MeatCuring", name: "Meat Curing", level: 1, kind: "craft", word: "MEATCURING", needs: [["Butchering", 75], ["Fishing", 75]] },
  { id: "Carpentry", name: "Carpentry", level: 1, kind: "craft", word: "CARVE", needs: [["Chopping", 75]] },
  { id: "Skill_Climb", name: "Climb", level: 1, kind: "skill", word: "CLIMB", needs: [["Chopping", 75]] },
  { id: "Skill_Autoclimb", name: "AutoClimb", level: 1, kind: "skill", word: "AUTOCLIMB", needs: [["Skill_Climb", 75]] },
  { id: "Proficiency_Axe", name: "Axe Proficiency", level: 1, kind: "weapon", needs: [["Chopping", 75]] },
  { id: "ScrimShaw", name: "Scrimshawing", level: 1, kind: "craft", word: "SCRIM", needs: [["Butchering", 75], ["Sculpting", 75]] },
  { id: "Proficiency_BluntWeapon", name: "Blunt Weapon Proficiency", level: 1, kind: "weapon", needs: [["Sculpting", 75]] },
  { id: "Dyeing", name: "Dyeing", level: 1, kind: "craft", word: "DYE", needs: [["Textiling", 75], ["Tanning", 75]] },
  { id: "Tailoring", name: "Tailoring", level: 1, kind: "craft", word: "KNIT", needs: [["Textiling", 75]] },
  { id: "CageBuilding", name: "Cage Building", level: 1, kind: "craft", word: "BUILDCAGE", needs: [["Carpentry", 75], ["Hunting", 75]] },
  { id: "AnimalHusbandry", name: "Animal Husbandry", level: 1, kind: "craft", word: "HUSBAND", needs: [["Shearing", 75], ["Bandaging", 75], ["CageBuilding", 75]] },
  { id: "Branding", name: "Branding", level: 1, kind: "craft", word: "BRANDING", needs: [["Shearing", 75], ["Bandaging", 75]] },
  { id: "Taxidermy", name: "Taxidermy", level: 1, kind: "craft", word: "STUFF", needs: [["Hunting", 75], ["Tanning", 75]] },
  { id: "MasterCooking", name: "Master Cooking", level: 30, kind: "craft", word: "MCOOK", needs: [["Cooking", 100], ["MasterForaging", 75]] },
  { id: "LeatherWorking", name: "Leather Working", level: 1, kind: "craft", word: "LEATHERWORK", needs: [["Hunting", 75], ["Tanning", 75]] },
  { id: "Baiting", name: "Baiting", level: 1, kind: "craft", word: "BAIT", needs: [["FishLore", 75]] },
  { id: "Trawling", name: "Trawling", level: 1, kind: "craft", word: "TRAWL", needs: [["FishLore", 75]] },
  { id: "MasterButchering", name: "Master Butchering", level: 30, kind: "craft", word: "MBUTCHERING", needs: [["Butchering", 100], ["Taxidermy", 75]] },
  { id: "Cobbling", name: "Cobbling", level: 1, kind: "craft", word: "COBBLE", needs: [["LeatherWorking", 75]] },
  { id: "Familiarity_Staff", name: "Staff Familiarity", level: 1, kind: "weapon", needs: [["Proficiency_Staff", 75]] },
  { id: "Skill_Trip", name: "Trip", level: 1, kind: "skill", word: "TRIP", needs: [["Familiarity_Staff", 75]] },
  { id: "MasterFishing", name: "Master Fishing", level: 30, kind: "craft", word: "MFISH", needs: [["Fishing", 100], ["Baiting", 75]] },
  { id: "Skill_Stability", name: "Stability", level: 1, kind: "skill", needs: [["Trawling", 75]] },
  { id: "Skill_Autocrawl", name: "AutoCrawl", level: 1, kind: "skill", word: "AUTOCRAWL", needs: [["Skill_Stability", 75]] },
  { id: "MasterTrawling", name: "Master Trawling", level: 30, kind: "craft", word: "MTRAWL", needs: [["Trawling", 100], ["MasterFishing", 75], ["Skill_Stability", 75]] },
  { id: "PaperMaking", name: "Paper Making", level: 1, kind: "craft", word: "PAPERMAKE", needs: [["Carpentry", 75]] },
  { id: "Fletching", name: "Fletching", level: 1, kind: "craft", word: "FLETCH", needs: [["Carpentry", 75]] },
  { id: "Wainwrighting", name: "Wainwrighting", level: 1, kind: "craft", word: "WAINWRIGHTING", needs: [["Carpentry", 75]] },
  { id: "InstrumentMaking", name: "Instrument Making", level: 1, kind: "craft", word: "INSTRUMENTMAKING", needs: [["Carpentry", 75]] },
  { id: "Familiarity_BluntWeapon", name: "Blunt Weapon Familiarity", level: 1, kind: "weapon", needs: [["Proficiency_BluntWeapon", 75]] },
  { id: "Blacksmithing", name: "Blacksmithing", level: 1, kind: "craft", word: "BLACKSMITH", needs: [["Smelting", 75]] },
  { id: "Construction", name: "Construction", level: 1, kind: "craft", word: "CONSTRUCT", needs: [["Carpentry", 75], ["Blacksmithing", 75]] },
  { id: "Familiarity_Shield", name: "Shield Familiarity", level: 1, kind: "weapon", needs: [["Carpentry", 75], ["Blacksmithing", 75]] },
  { id: "GlassBlowing", name: "Glass Blowing", level: 1, kind: "craft", word: "GLASSBLOW", needs: [["Pottery", 75]] },
  { id: "JewelMaking", name: "Jewel Making", level: 1, kind: "craft", word: "JEWEL", needs: [["Pottery", 75]] },
  { id: "Siegecraft", name: "Siegecrafting", level: 1, kind: "craft", word: "SIEGECRAFT", needs: [["Fletching", 75]] },
  { id: "Boatwright", name: "Boatwrighting", level: 1, kind: "craft", word: "BOATWRIGHTING", needs: [["Wainwrighting", 75]] },
  { id: "MasterChopping", name: "Master Wood Chopping", level: 30, kind: "craft", word: "MCHOP", needs: [["Chopping", 100], ["Siegecraft", 75], ["Boatwright", 75]] },
  { id: "Shipwright", name: "Ship Building", level: 1, kind: "craft", word: "SHIPBUILD", needs: [["Boatwright", 75], ["Trawling", 75]] },
  { id: "ClanShipwrighting", name: "Clan Ship Building", level: 7, kind: "craft", word: "CLANSHIPBUILD", needs: [["Shipwright", 75]] },
  { id: "Weaving", name: "Weaving", level: 1, kind: "craft", word: "WEAVING", needs: [["Chopping", 75], ["Skill_WildernessLore", 75]] },
  { id: "PlantLore", name: "Plant Lore", level: 1, kind: "craft", word: "PLANTLORE", needs: [["Herbology", 75], ["Floristry", 75]] },
  { id: "Skill_FindHome", name: "Find Home", level: 1, kind: "skill", word: "FINDHOME", needs: [["Construction", 75], ["Masonry", 75]] },
  { id: "Skill_FindShip", name: "Find Ship", level: 1, kind: "skill", word: "FINDSHIP", needs: [["Fishing", 75], ["Shipwright", 75]] },
  { id: "Proficiency_Hammer", name: "Hammer Proficiency", level: 1, kind: "weapon", needs: [["Blacksmithing", 75]] },
  { id: "Familiarity_Hammer", name: "Hammer Familiarity", level: 1, kind: "weapon", needs: [["Proficiency_Hammer", 75]] },
  { id: "Fighter_HammerRing", name: "HammerRing", level: 1, kind: "skill", word: "HAMMERRING", needs: [["Familiarity_Hammer", 75]] },
  { id: "MasterShearing", name: "Master Shearing", level: 30, kind: "craft", word: "MSHEAR", needs: [["Shearing", 100], ["AnimalHusbandry", 75]] },
  { id: "Skill_Cage", name: "Cage", level: 1, kind: "skill", word: "CAGE", needs: [["AnimalHusbandry", 75]] },
  { id: "Skill_MountedCombat", name: "Mounted Combat", level: 1, kind: "skill", needs: [["AnimalHusbandry", 75]] },
  { id: "Herding", name: "Herding", level: 1, kind: "craft", word: "HERD", needs: [["Skill_MountedCombat", 75]] },
  { id: "Shepherding", name: "Shepherding", level: 1, kind: "craft", word: "SHEPHERD", needs: [["Shearing", 75]] },
  { id: "Embroidering", name: "Embroidering", level: 1, kind: "craft", word: "EMBROIDER", needs: [["Skill_Write", 50], ["Tailoring", 75], ["LeatherWorking", 75]] },
  { id: "MasterFloristry", name: "Master Floristry", level: 30, kind: "craft", word: "MFLORISTRY", needs: [["Floristry", 100], ["Painting", 75]] },
  { id: "MasterHerbology", name: "Master Herbology", level: 30, kind: "craft", word: "MHERBOLOGY", needs: [["Herbology", 100], ["MasterCooking", 75], ["MasterFoodPrep", 75]] },
  { id: "MasterMycology", name: "Master Mycology", level: 30, kind: "craft", word: "MMYCOLOGY", needs: [["Mycology", 100], ["MasterCooking", 75], ["MasterFoodPrep", 75]] },
  { id: "Thief_Lore", name: "Lore", level: 1, kind: "skill", word: "LORE", needs: [["Skill_Write", 75], ["PaperMaking", 75]] },
  { id: "Proficiency_Ranged", name: "Ranged Weapon Proficiency", level: 1, kind: "weapon", needs: [["Fletching", 100]] },
  { id: "Familiarity_Ranged", name: "Ranged Weapon Familiarity", level: 1, kind: "weapon", needs: [["Proficiency_Ranged", 75]] },
  { id: "Fighter_CoverDefence", name: "Cover Defence", level: 1, kind: "skill", needs: [["Proficiency_Ranged", 75]] },
  { id: "Skill_WandUse", name: "Wands", level: 1, kind: "skill", needs: [["Speculate", 75]] },
  { id: "MasterDrilling", name: "Master Drilling", level: 30, kind: "craft", word: "MDRILL", needs: [["Drilling", 100], ["Speculate", 75]] },
  { id: "StaffMaking", name: "Staff Making", level: 1, kind: "craft", word: "STAFFMAKE", needs: [["Familiarity_Staff", 75], ["Thief_Lore", 75]] },
  { id: "WandMaking", name: "Wand Making", level: 1, kind: "craft", word: "WANDMAKE", needs: [["Skill_WandUse", 75], ["Thief_Lore", 75]] },
  { id: "Rodsmithing", name: "Rodsmithing", level: 1, kind: "craft", word: "RODSMITH", needs: [["Skill_WandUse", 75], ["Thief_Lore", 75]] },
  { id: "Proficiency_Natural", name: "Natural Weapon Proficiency", level: 1, kind: "weapon", needs: [["AnimalHusbandry", 75]] },
  { id: "Fighter_Kick", name: "Kick", level: 1, kind: "skill", word: "KICK", needs: [["Proficiency_Natural", 75]] },
  { id: "Skill_Dodge", name: "Dodge", level: 1, kind: "skill", needs: [["Proficiency_Natural", 75]] },
  { id: "Weaponsmithing", name: "Weaponsmithing", level: 1, kind: "craft", word: "WEAPONSMITH", needs: [["Blacksmithing", 75]] },
  { id: "Armorsmithing", name: "Armorsmithing", level: 1, kind: "craft", word: "ARMORSMITH", needs: [["Blacksmithing", 75]] },
  { id: "LockSmith", name: "Locksmithing", level: 1, kind: "craft", word: "LOCKSMITH", needs: [["Blacksmithing", 75]] },
  { id: "Scrapping", name: "Scrapping", level: 1, kind: "craft", word: "SCRAP", needs: [["Armorsmithing", 75], ["LeatherWorking", 75], ["Tailoring", 75]] },
  { id: "MasterTailoring", name: "Master Tailoring", level: 30, kind: "craft", word: "MASTERKNIT", needs: [["Tailoring", 100], ["Scrapping", 75]] },
  { id: "MasterLeatherWorking", name: "Master Leather Working", level: 30, kind: "craft", word: "MASTERLEATHERWORKING", needs: [["LeatherWorking", 100], ["Scrapping", 75]] },
  { id: "MasterArmorsmithing", name: "Master Armorsmithing", level: 30, kind: "craft", word: "MARMORSMITH", needs: [["Armorsmithing", 100], ["Scrapping", 75]] },
  { id: "Costuming", name: "Costuming", level: 1, kind: "craft", word: "COSTUME", needs: [["Tailoring", 75]] },
  { id: "MasterDistilling", name: "Master Distilling", level: 30, kind: "craft", word: "MDISTILLING", needs: [["Distilling", 100], ["Herbology", 75]] },
  { id: "Thief_Appraise", name: "Appraise", level: 1, kind: "skill", word: "APPRAISE", needs: [["JewelMaking", 75]] },
  { id: "Lacquerring", name: "Lacquering", level: 1, kind: "craft", word: "LACQUERING", needs: [["JewelMaking", 75]] },
  { id: "Proficiency_Sword", name: "Sword Proficiency", level: 1, kind: "weapon", needs: [["Weaponsmithing", 75]] },
  { id: "Skill_AttackHalf", name: "Half Attack", level: 1, kind: "skill", needs: [["Proficiency_Sword", 75]] },
  { id: "Familiarity_Sword", name: "Sword Familiarity", level: 1, kind: "weapon", needs: [["Proficiency_Sword", 75]] },
  { id: "Skill_Parry", name: "Parry", level: 1, kind: "skill", needs: [["Proficiency_Sword", 100]] },
  { id: "MasterWeaponsmithing", name: "Master Weaponsmithing", level: 30, kind: "craft", word: "MWEAPONSMITH", needs: [["Weaponsmithing", 100], ["Familiarity_Sword", 75]] },
  { id: "Engraving", name: "Engraving", level: 1, kind: "craft", word: "ENGRAVE", needs: [["Skill_Write", 50], ["Blacksmithing", 75]] },
  { id: "MasterCostuming", name: "Master Costuming", level: 30, kind: "craft", word: "MASTERCOSTUME", needs: [["Costuming", 100], ["PaperMaking", 75]] },
  { id: "Merchant", name: "Marketeering", level: 1, kind: "craft", word: "MARKET", needs: [["Engraving", 75], ["Embroidering", 75]] },
  { id: "Skill_Haggle", name: "Haggle", level: 1, kind: "skill", word: "HAGGLE", needs: [["Merchant", 75], ["Thief_Appraise", 75]] },
  { id: "Excavation", name: "Excavation", level: 1, kind: "craft", word: "EXCAVATE", needs: [["Masonry", 75]] },
  { id: "MasterMining", name: "Master Mining", level: 30, kind: "craft", word: "MMINE", needs: [["Mining", 100], ["Excavation", 75]] },
  { id: "MasterDigging", name: "Master Gem Digging", level: 30, kind: "craft", word: "MGDIG", needs: [["Digging", 100], ["Excavation", 75]] },
  { id: "Painting", name: "Painting", level: 1, kind: "craft", word: "PAINT", needs: [["Lacquerring", 75], ["Dyeing", 75]] },
  { id: "Skill_Warrants", name: "Warrants", level: 1, kind: "skill", word: "WARRANTS", needs: [["Distilling", 75], ["Painting", 75]] },
  { id: "Familiarity_Axe", name: "Axe Familiarity", level: 1, kind: "weapon", needs: [["Proficiency_Axe", 75]] },
  { id: "SmokeRings", name: "Smoke Rings", level: 1, kind: "craft", word: "SMOKERINGS", needs: [["Herbology", 75]] },
  { id: "Decorating", name: "Decorating", level: 1, kind: "craft", word: "DECORATE", needs: [["Painting", 75], ["Construction", 75]] },
  { id: "Embellishing", name: "Embellishing", level: 1, kind: "craft", word: "EMBELLISH", needs: [["Armorsmithing", 75], ["LeatherWorking", 75], ["Tailoring", 75]] },
  { id: "Thief_StrategicRetreat", name: "Strategic Retreat", level: 1, kind: "skill", word: "FREEFLEE", needs: [["Skill_Autoclimb", 75], ["Skill_Autoswim", 75], ["Skill_Autocrawl", 75]] },
  { id: "Skill_ShipLore", name: "Ship Lore", level: 1, kind: "skill", word: "SHIPLORE", needs: [["Shipwright", 75]] },
  { id: "LegendaryWeaponsmithing", name: "Legendary Weaponsmithing", level: 60, kind: "craft", word: "LWEAPONSMITH", needs: [["MasterWeaponsmithing", 100]] },
  { id: "MasterDyeing", name: "Master Dyeing", level: 30, kind: "craft", word: "MASTERDYEING", needs: [["Dyeing", 100]] },
  { id: "MasterLacquerring", name: "Master Lacquering", level: 30, kind: "craft", word: "MASTERLACQUERING", needs: [["Lacquerring", 100]] },
];
